[platformio]
default_envs = main

[versions]
firmware = 0.1.33_Beta
recovery = 0.1.4

[env]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  knolleary/PubSubClient@^2.8
  arduino-libraries/Ethernet@^2.0.2
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/RTClib@^2.1.4
build_flags =
  -Iinclude
  -DFIRMWARE_VERSION=\"${versions.firmware}\"
  -DRECOVERY_VERSION=\"${versions.recovery}\"
  -DCORE_DEBUG_LEVEL=1
  -DARDUINOJSON_USE_LONG_LONG=1
  -DMQTT_MAX_PACKET_SIZE=6144
  -Wall
  -Wextra

[env:main]
build_src_filter = +<main/> -<recovery/>
board_build.app_partition_name = ota_0
board_upload.offset_address = 0x90000
board_upload.maximum_size = 3538944
build_flags =
  ${env.build_flags}
  -DAPP_MAIN

[env:recovery]
build_src_filter = +<recovery/> -<main/>
board_build.app_partition_name = factory
board_upload.offset_address = 0x10000
board_upload.maximum_size = 524288
lib_ignore =
  PubSubClient
  Ethernet
  RTClib
build_flags =
  ${env.build_flags}
  -DAPP_RECOVERY
